djcode/ACS/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import ACS.views as views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #url(r'^admin/', include(admin.site.urls)),
	#url(r'^time/plus/(\d{1,2})/$', hours_ahead),
	url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
	url(r'^cr/(add|del|mod|)?$', views.TeachingResourse),
	url(r'^acs/(automatic)?$', views.CourseArrange),
	url(r'^mca/(add_cl|del_cl|)?$', views.CourseApply),
	url(r'^(admin|teacher)?$', views.Index),
	url(r'^tcs/', views.CourseSearch),
	url(r'^ci/', views.ClassroomInquiry),
	url(r'^course/(add_cz|del_cz|add_cl|del_cl|)?$', views.CourseOperation),
	url(r'^logout/', views.Logout),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 

djcode/IMS/urls.py
__author__ = 'Adward'

"""djcode URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from IMS import views, profile, course_views, user_views, log_views, forget_pwd

urlpatterns = [
    url(r'^login/$', views.loggingin), #by adward
    #url(r'^hello/', views.startup),
    url(r'^add_user/', views.add_user), #by adward
    url(r'^user_added/', views.user_added), #by adward
    url(r'^user_auth/', views.user_auth), #by adward
    url(r'^home/$', views.home), #by adward
    url(r'^logout/$', views.loggingout), #by adward
    url(r'^home/profile/$', profile.profile), #by adward
    url(r'^home/profile/changeUserInfo/$', profile.changeUserInfo), #by xyh
    url(r'^home/profile/changePasswd/$', profile.changePasswd), #by xyh
    url(r'^home/profile/changePhoto/$', profile.changePhoto), #by xyh
    url(r'^log/$', log_views.all_log), # by xyh
    url(r'^log/deleteLog/$', log_views.delete_all_log), # by xyh
    url(r'^course/$', course_views.courseMain), #by saltless
    url(r'^course/add/$', course_views.courseAdd), #by saltless
    url(r'^course/delete/$', course_views.courseDelete), #by saltless
    url(r'^course/modify/$', course_views.courseModify), #by saltless
    url(r'^user/$', user_views.userMain), #by Henry
    url(r'^user/add_faculty/$', user_views.facultyAdd), #by Henry
    url(r'^user/delete_faculty/$', user_views.facultyDelete), #by Henry
    url(r'^user/modify_faculty/$', user_views.facultyModify), #by Henry
    url(r'^user/add_student/$', user_views.studentAdd), #by Henry
    url(r'^user/delete_student/$', user_views.studentDelete), #by Henry
    url(r'^user/modify_student/$', user_views.studentModify), #by Henry
    url(r'^user/add_admin/$', user_views.adminAdd), #by Henry
    url(r'^user/delete_admin/$', user_views.adminDelete), #by Henry
    url(r'^user/modify_admin/$', user_views.adminModify), #by Henry
    url(r'^forget_pwd/$', forget_pwd.forget_pwd), #by adward
    url(r'^reset_pwd_mail/$', forget_pwd.reset_pwd_mail), #by adward
    url(r'^reset_pwd/(?P<key>[0-9a-zA-Z]{20})/$', forget_pwd.reset_pwd), #by adward
]

## For upload user photos
urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djcode/djcode/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.views as auth_views
from IMS.views import startup
from djcode import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns #by SMS

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ims/', include('IMS.urls')),
    url(r'^SM/', include('dbtest.urls')), #by SMS
    url(r'^$', startup),
    url(r'^ACS/', include('ACS.urls')),
    #url(r'^', include('teacher.url')), #by OnlineTest
]

urlpatterns += staticfiles_urlpatterns() #by SMS

djcode/IMS/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.

#class Login_info: handled by Django User
import os
from django.conf import settings

DEFAULT_PHOTO_DIR = os.path.join("photo", "default.jpg")


def get_photo_file_name(instance, filename):
    # print instance.id
    # print filename
    filename = filename.encode('utf-8')
    newFilename = os.path.join("photo", str(instance.id)) + "." + str(filename).split('.')[-1]
    newFullFilename = os.path.join(settings.MEDIA_ROOT, newFilename)
    if os.path.exists(newFullFilename):
        os.remove(newFullFilename)
    return newFilename

class Student_user(models.Model):
    '''
    | id | contact | name | gender | college | major | grade | gpa | credits |
    |---|---|---|---|---|---|---|---|---|
    | CHARACTER(10) | VARCHAR(11) | VARCHAR(20) | BOOLEAN | VARCHAR(50) | VARCHAR(50) | INTEGER | FLOAT | FLOAT |
    '''
    id = models.CharField(max_length=10, primary_key=True)
    contact = models.CharField(max_length=11,default='18812345678')
    name = models.CharField(max_length=20,default='张三')
    gender = models.BooleanField(default=True)
    college = models.CharField(max_length=50,default='计算机科学与技术学院')
    major = models.CharField(max_length=50,default='计算机科学与技术')
    grade = models.IntegerField(default=3)
    gpa = models.FloatField(default=4.0)
    credits = models.FloatField(default=100.0)
    isSpecial = models.BooleanField(default=False)
    photo = models.FileField(upload_to=get_photo_file_name, default=DEFAULT_PHOTO_DIR)

    def __unicode__(self):
        return u'id:%s, contact:%s, name:%s, gender:%d, college:%s, major:%s, grade:%s, gpa:%f, credits:%f'%(self.id, self.contact,self.name,self.gender, self.college,self.major,self.grade, self.gpa, self.credits)
        # return 'id:' + self.id

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ("student_manage", "Can manage stu user info"),
        )


class Faculty_user(models.Model):
    '''
    | id | contact | name | gender | college | major | degree | title |
    |---|---|---|---|---|---|---|---|
    | CHARACTER(6) | VARCHAR(11) | VARCHAR(20) | BOOLEAN | VARCHAR(50) | VARCHAR(50) | VARCHAR(20) | VARCHAR(20) |
    '''
    id = models.CharField(max_length=6, primary_key=True)
    contact = models.CharField(max_length=11, default= "18812345678")
    name = models.CharField(max_length=20,default= "张三")
    gender = models.BooleanField(default=0)
    college = models.CharField(max_length=50,default="计算机科学与技术学院")
    major = models.CharField(max_length=50,default='计算机科学与技术')
    degree = models.CharField(max_length=20,default='博士')
    title = models.CharField(max_length=20, default="研究员")
    isSpecial = models.BooleanField(default=False)
    photo = models.FileField(upload_to=get_photo_file_name, default=DEFAULT_PHOTO_DIR)
    introduce = models.CharField(max_length=300, default="") #by CCS

    def __unicode__(self):
        return u'id:%s, contact:%s, name:%s, gender:%d, college:%s, major:%s, degree:%s, title:%s'%(self.id, self.contact,self.name,self.gender, self.college,self.major,self.degree, self.title)
        # return 'id:' + self.id

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ("faculty_manage", "Can manage faculty user info"),
        )

class Admin_user(models.Model):
    '''
    | id | contact | name | gender | college |
    |---|---|---|---|---|
    | CHARACTER(3) | VARCHAR(11) | VARCHAR(20) | BOOLEAN | VARCHAR(50) |
    '''
    id = models.CharField(max_length=3, primary_key=True)
    contact = models.CharField(max_length=11,default="18812345678")
    name = models.CharField(max_length=20, default="张三")
    gender = models.BooleanField(default=0)
    college = models.CharField(max_length=50, default="all") #default for superadmin
    photo = models.FileField(upload_to=get_photo_file_name, default=DEFAULT_PHOTO_DIR)

    def __unicode__(self):
        return u'id:%s, contact:%s, name:%s, gender:%d, college:%s'%(self.id, self.contact,self.name,self.gender, self.college)
        # return 'id:' + self.id

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ("admin_manage", "Can manage admin user info"),
        )

class Course_info(models.Model):
    '''
    | id | name | credits | semester | textbook | college |
    |---|---|---|---|---|---|
    | CHARACTER(8) | VARCHAR(110) | FLOAT | INTEGER | VARCHAR(110) | VARCHAR(50) |
    '''
    id = models.CharField(max_length=8, primary_key=True)
    name = models.CharField(max_length=110)
    credits = models.FloatField(default=0)
    semester = models.IntegerField(default=0)
    textbook = models.CharField(max_length=110)
    college = models.CharField(max_length=50)
    course_type = models.IntegerField(default=0) #必修、选项和通识，根据选课组要求加入
    introduce = models.CharField(max_length=300, default="")

    def __unicode__(self):
        return u'id:%s, name:%s, credits:%f, semester:%d, textbook:%s, college:%s, course_type:%d'%(self.id, self.name, self.credits, self.semester, self.textbook, self.college, self.course_type)

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ("course_manage", "Can manage basic course info"),
        )

class Class_info(models.Model):
    '''
    | class_id | id | teacher | time | room | examdate | examtime | examroom | capacity |
    |---|---|---|---|---|---|---|---|---|
    | CHARACTER(10) | CHARACTER(8) | VARCHAR(20) | INTEGER | VARCHAR(20) | DATETIME(TEXT) | INTEGER | VARCHAR(20) | INTEGER |
    '''
    id = models.CharField(max_length=10, primary_key=True)
    course = models.ForeignKey(Course_info, related_name='class_course')
    teacher = models.ForeignKey(Faculty_user)
    time = models.CharField(max_length=20) #by CCS: type integer to char
    room = models.CharField(max_length=20)
    examdate = models.CharField(max_length=10, default="0000000000")
    examtime = models.CharField(max_length=10, default="0000000000")
    examroom = models.CharField(max_length=20, default="00000000000000000000")
    capacity = models.IntegerField(default=0)
    semester = models.IntegerField(default=0) #开课学期
    remain = models.IntegerField(default=0) #选课剩余容量
    year = models.IntegerField(default=2015) #年份（学年）
    language = models.IntegerField(default=0) #中文、英文、双语

    def __unicode__(self):
        return u'class_id:%s, teacher:%s, time:%d, room:%s, examdate:%s, examtime:%d, examroom:%s, capacity:%d, semester:%d, remain:%d, year:%d, language:%d'%(self.id, self.teacher, self.time, self.room, self.examdate, self.examtime, self.examroom, self.capacity, self.semester, self.remain, self.year, self.language)
        # return u'id:%s, course:%s, teacher:%s, time:%s, room:%s, examdate:%s, examtime:%d, examroom:%s, capacity:%d, semester:%d, remain:%d, year:%d, language:%d'%(self.id, self.course, self.teacher, self.time, self.room, self.examdate, self.examtime, self.examroom, self.capacity, self.semester, self.remain, self.year, self.language)

    def __str__(self):
        return self.id

class Class_table(models.Model):
    '''
    | student_id | class_id |
    |---|---|
    | CHARACTER(10) | CHARACTER(10) |
    '''
    id = models.CharField(max_length=10, primary_key=True)
    student = models.ForeignKey(Student_user)
    Class = models.ForeignKey(Class_info)
    status = models.BooleanField(default=0)
    def __str__(self):
        return (self.id)

class FindPass(models.Model):
    username = models.CharField(max_length=20)
    activation_key = models.CharField(max_length=20)
    timestamp = models.CharField(max_length=10) #int part
    #date = models.DateField(auto_now_add=True)

djcode/IMS/views.py
# -*- coding: utf-8 -*-

from IMS.head import *
from IMS.models import Student_user, Faculty_user, Admin_user
from django.http import Http404
from django import forms
from django.forms.util import ErrorList

LEN_OF_STUDENT_ID = 10
LEN_OF_FACULTY_ID = 6
LEN_OF_ADMIN_ID = 3

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    passwd = forms.CharField(max_length=20)

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        _username = cleaned_data.get('username', '')
        _passwd = cleaned_data.get('passwd', '')
        if not User.objects.filter(username=_username):
            error_msg = ["用户不存在！"]
            super(LoginForm, self).errors['username'] = ErrorList(error_msg)
        else:
            user = authenticate(username=_username, password=_passwd)
            if user is None:
                error_msg = ["密码错误!"]
                super(LoginForm, self).errors['passwd'] = ErrorList(error_msg)
                #raise forms.ValidationError('密码错误')
        return cleaned_data

def startup(request):
    if not Group.objects.filter(name='student'):
        group = Group(name='student')
        group.save()
    if not Group.objects.filter(name='teacher'):
        group = Group(name='teacher')
        group.save()
    if not Group.objects.filter(name='admin'):
        group = Group(name='admin')
        group.save()

    local_path = os.path.dirname(__file__) #IMS/
    if not os.path.exists(os.path.join(local_path, 'log')):
        os.mkdir(os.path.join(local_path, 'log'))
    return HttpResponseRedirect('ims/login/')

def loggingin(request):
    #print request.user
    if not request.user.is_authenticated():
        form = LoginForm()
        t = get_template('login.html')
        c = RequestContext(request, {'form': form})
        return HttpResponse(t.render(c))
    else:
        return HttpResponseRedirect('../home/')

@login_required
def loggingout(request):
    logout(request)
    #return render(request, 'logout.html')
    return HttpResponseRedirect('../login/')

@login_required
def add_user(request):
    print("add_user")
    c = {}
    c.update(csrf(request))
    return render_to_response('add_user.html', c)

@login_required
def user_added(request):
    c = {}
    c.update(csrf(request))
    print(request.POST)
    usertype = request.POST['user_type']
    userid = request.POST['user_id']
    userpasswd = '123456' #default
    print("haha")
    user = User.objects.create_user(userid, userid+'@zju.edu.cn', userpasswd)
    if usertype == 'Admin':
        user.user_permissions.add()
    elif usertype == 'Student':
        if len(userid) != 10:
            c.update({'idLenInvalid':1})
        else:
            newStudent = Student_user(id=userid)
            newStudent.save()
            #print 'newStudent:',newStudent
    elif usertype == 'Faculty':
        pass
        #TODO add a faculty to database
    user.save()
    return render_to_response('add_user.html', c)

@csrf_exempt
def user_auth(request):
    #c = {}
    #c.update(csrf(request))
    form = ""
    if request.method == 'POST':
        form = LoginForm(request.POST)
    else:
        form = LoginForm()

    if form.is_valid():
        _username = form.cleaned_data['username']
        _passwd = form.cleaned_data['passwd']
        user = authenticate(username = _username, password = _passwd)
        if user is not None:
            if user.is_active: #valid, active and authenticated
                login(request, user)
                return HttpResponseRedirect('../home/')  #TODO: csrf

    # else, back to login page
    t = get_template('login.html')
    c = RequestContext(request, {'form': form})
    return HttpResponse(t.render(c))

@csrf_exempt
@login_required
def home(request):
    user_name = str(request.user)  # user Id
    user_name_len = user_name.__len__()
    isStudent, isFaculty, isAdmin, isSuper = 0, 0, 0, 0

    if user_name_len == LEN_OF_STUDENT_ID:
        usrInfo = Student_user.objects.get(id=user_name)
        isStudent = 1
        #return render_to_response('home_panel.html', {"isStudent": 1, "usrInfo": usrInfo})
    elif user_name_len == LEN_OF_FACULTY_ID:
        usrInfo = Faculty_user.objects.get(id=user_name)
        isFaculty = 1
        #return render_to_response('home_panel.html', {"isFaculty": 1, "usrInfo": usrInfo})
    elif user_name_len == LEN_OF_ADMIN_ID:
        usrInfo = Admin_user.objects.get(id=user_name)
        isAdmin = 1
        if usrInfo.college == "all":
            isSuper = 1
    else:
        # wrong id length
        raise Http404()

    t = get_template('home_panel.html')
    c_dict = {"usrInfo": usrInfo, "isStudent": isStudent, "isFaculty": isFaculty,
              "isAdmin": isAdmin, "isSuper": isSuper}
    if not isAdmin:
        if usrInfo.isSpecial:
            c_dict.update({"isSpecial": 1})
            if request.user.has_perm('IMS.student_manage'):
                c_dict.update({"manageStudent": 1})
            elif request.user.has_perm('IMS.faculty_manage'):
                c_dict.update({"manageFaculty": 1})
            elif request.user.has_perm('IMS.admin_manage'):
                c_dict.update({"manageAdmin": 1})
            elif request.user.has_perm('IMS.course_manage'):
                c_dict.update({"manageCourse": 1})
    c = RequestContext(request, c_dict)
    return HttpResponse(t.render(c))

djcode/IMS/templates/AccessFault.html
<!-- by xyh-->

<!DOCTYPE html>
<html>
<head>
	<title>Access Prohibited</title>
</head>
<body>
	<h1>Access Prohibited.</h1>
	<p></p>
	<p>Please check your login status.</p>
	<a href="/ims/home/">back to homepage</a>
</body>
</html>

djcode/IMS/templates/AddFaculty.html
<!-- #by henry -->

<!DOCTYPE html>
<html>

<style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }

    .input-group {
        margin-top: 15px;
    }
    .btn {
        margin-top: 15px;
    }
    .alert {
        width: 50%;
    }
</style>

<head lang="en">
    <meta charset="UTF-8">
    <title>Add faculty</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
</head>
<body>
<br/>
<div class="container">
    <nav class="navbar" role="navigation">
        <div>
            <ul class="nav nav-tabs navbar-left">
                <li role="presentation"><a href="/ims/home/">个人首页</a></li>
                <li role="presentation"><a href="/ims/course/">课程信息管理</a></li>
                <li role="presentation" class="active"><a href="/ims/user/">用户信息管理</a></li>
                <li role="presentation"><a href="/ims/home/profile/">个人信息管理</a></li>
                <li role="presentation"><a href="/ims/logout/">退出登录</a></li>
            </ul>
            <ul class="nav navbar-right">

            </ul>
        </div>
    </nav>

    <div class="page-header">
        <h1>New Faculty Infomation</h1>
    </div>

    {% if addIsDone %}
        <div class="alert alert-success">
            Faculties added successfully.
        </div>
    {% endif %}

    {% if form.errors %}
        <div class="alert alert-warning">
            Please correct the error{{ form.errors|pluralize }} below.
        </div>
    {% endif %}

    <div class="form-group" style="width: 50%;">
        <form id="submit_single" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="submit" value="Add This Faculty" class="btn btn-default">
            <br/><br/>
            <input type="checkbox" id="id_isSpecial" name="isSpecial" onclick="toggleSpecialStatus()">
            <label for="id_isSpecial"> Is Special? </label>

            <div class="btn-group" data-toggle="buttons" id="authority">
                <button class="btn btn-default" id="au1" disabled="disabled">
                    <input type="checkbox" id="id_canManageCourses" name="canManageCourses"> Can Manage Courses
                </button>
                <button class="btn btn-default" id="au2" disabled="disabled">
                    <input type="checkbox" id="id_canManageStudents" name="canManageStudents"> Can Manage Students
                </button>
                <button class="btn btn-default" id="au3" disabled="disabled">
                    <input type="checkbox" id="id_canManageFaculties" name="canManageFaculties"> Can Manage Faculties
                </button>
            </div>

            <div class="input-group">
                <span class="input-group-addon"> College </span>
                {% if isSuper %}
                    <select id="id_college" name="college" class="form-control">
                        {% for col in stu_colleges %}
                            <option value="{{ col }}">{{ col }}</option>
                        {% endfor %}
                    </select>
                {% else %}
                    {{ form.college }}
                {% endif %}
            </div>

            <div class="input-group">
                <span class="input-group-addon"> Gender </span>
                <select id="id_gender" name="gender" class="form-control">
                    <option value="M">男</option>
                    <option value="F">女</option>
                </select>
            </div>
        </form>

        <form id="submit_csv" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="submit" value="Add Faculties from CSV" class="btn btn-default">
            <br/><br/>
            <input type="file" name="file" value="Upload" role="button">
        </form>
    </div>

    {% if multiAdd %}
        <form id='multiAdd' action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="alert alert-info">
                Sure to add following faculties?
            </div>
            <table class="table table-striped table-hover">
                <tr>
                    <th>Id</th>
                    <th>Contact</th>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>College</th>
                    <th>Major</th>
                    <th>Degree</th>
                    <th>Title</th>
                    <th>IsSpecial</th>
                </tr>
                {% for term in terms %}
                    <tr>
                        <th>{{ term.0 }}</th>
                        <th>{{ term.1 }}</th>
                        <th>{{ term.2 }}</th>
                        <th>{{ term.3 }}</th>
                        <th>{{ term.4 }}</th>
                        <th>{{ term.5 }}</th>
                        <th>{{ term.6 }}</th>
                        <th>{{ term.7 }}</th>
                        <th>{{ term.8 }}</th>
                    </tr>
                {% endfor %}
            </table>
            <input type="button" name="multiAddConfirm" value="Confirm" class="btn btn-info" onclick="javascript:f('multiAdd')">
            <input type="submit" name="multiAddCancel" value="Cancel" class="btn btn-default">
            <input type="hidden" name="file">
        </form>
    {% endif %}

    {% if errorExist %}
        <div class="alert alert-danger">
            The followings were not successfully added.
        </div>
        <table class="table table-striped table-hover">
            <tr>
                <th>FAULT</th>
                <th>ID</th>
                <th>Contact</th>
                <th>Name</th>
                <th>Gender</th>
                <th>College</th>
                <th>Major</th>
                <th>Degree</th>
                <th>Title</th>
            </tr>
            {% for term in existed %}
                <tr>
                    <th>{{ term.8 }}</th>
                    <th>{{ term.0 }}</th>
                    <th>{{ term.1 }}</th>
                    <th>{{ term.2 }}</th>
                    <th>{{ term.3 }}</th>
                    <th>{{ term.4 }}</th>
                    <th>{{ term.5 }}</th>
                    <th>{{ term.6 }}</th>
                    <th>{{ term.7 }}</th>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
</body>
</html>

<script type="text/javascript">
    var isSpecial = false;

    function f(a) {
        var tables = document.getElementsByTagName("th");
        var form = document.getElementById(a);
        var s = "";
        for (var i = 8; i < tables.length; i ++) {
            s += tables[i].innerText + ",";
        };
        form.file.value = s;
        form.submit();
    }

    {% for field in form %}
        var label = "{{ field.label }}";
        if (label=="Isspecial" || label=="Canmanagecourses"
                || label=="Canmanagestudents" || label=="Canmanagefaculties" || label=="Photo"
                || label=="Gender" || label=="College") {

        }
        else {
            var input_group = $("<div class='input-group {% if field.errors %}has-error{% endif %}'></div>");
            var span = $("<span class='input-group-addon'> {{ field.label }} </span>");
            var field_body = $('{{ field }}');
            field_body.attr({"class": "form-control", "required": ""});
            input_group.append(span).append(field_body);
            $("#submit_single").append(input_group);
        }
    {% endfor %}

    //only super admin can change its college info field
    {% if not isSuper %}
        $("#id_college").attr({"class": "form-control", "readonly": ""});
    {% endif %}

    function toggleSpecialStatus() {
        if (isSpecial) {
            $("#au1").attr("disabled", "");
            $("#au2").attr("disabled", "");
            $("#au3").attr("disabled", "");
            isSpecial = false;
        }
        else {
            $("#au1").removeAttr("disabled");
            $("#au2").removeAttr("disabled");
            $("#au3").removeAttr("disabled");
            isSpecial = true;
        }
    }
</script>
</html>

djcode/IMS/templates/add_user.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>LOGIN_TEST</title>
    <link href="../../static/css/bootstrap.min.css" rel="stylesheet">
    <script src="../../static/js/jquery.min.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>
</head>
<body onload="ChooseOutput()">

<div class="container">
    <div class="row" align="middle">
        <div class="col" align="middle">
            <form role="form" action="../user_added/" method="post"> {% csrf_token %}
                <label for="name">请选择用户类型</label>
                <select class="form-control" id="usertype">
                    <option>Faculty</option>
                    <option>Student</option>
                </select>
                <br/>
                <br/>
                <div class="input-prepend">
                    <span class="add-on"><span class="icon-lock"></span></span>
                    ID:<input class="span2" placeholder="请输入用户ID" id="userid" type="text" />
                </div>
                <br/>
                <p id="indicator"></p>
                <br/>
                <button type="button" class="btn btn-default"
                        onclick="judgeInput()">完成</button>
            </form>
        </div>
    </div>
</div>


</body>
</html>

<script>
    var usertype, userid;

    function ChooseOutput() {} //TODO: ChooseOutput blank??? by Henry

    function judgeInput() {
        usertype = document.getElementById("usertype").value;
        userid = document.getElementById("userid").value;
        if (usertype=="Admin") {
            document.getElementById("indicator").innerHTML = "该功能尚未开通，管理员用户只能由root后台添加！";
        }
        else if (usertype=="Faculty") {
            if (userid.length!=6) {
                document.getElementById("indicator").innerHTML = "教职工用户ID长度为6位！";
            }
            else {
                $.ajaxSetup({
                     data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
                }); //cannot be written in outer *.js but must be embedded in template
                $.post("../user_added/", { user_type: usertype, user_id: userid});
                document.getElementById("indicator").innerHTML = "";
            }
        }
        else if (usertype=="Student") {
            if (userid.length!=10) {
                document.getElementById("indicator").innerHTML = "学生用户ID长度为10位！";
            }
            else {
                $.ajaxSetup({
                     data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
                }); //cannot be written in outer *.js but must be embedded in template
                $.post("../user_added/", { user_type: usertype, user_id: userid});
                document.getElementById("indicator").innerHTML = "";
            }
        }
        else {
            document.getElementById("indicator").innerHTML = "输入无法识别！";
        }
    }

</script>

djcode/IMS/templates/change_passwd_success.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    修改成功！
    <br/>
    <a href="/">Go Login Again>>></a>

</body>
</html>