djcode/ACS/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import ACS.views as views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #url(r'^admin/', include(admin.site.urls)),
	#url(r'^time/plus/(\d{1,2})/$', hours_ahead),
	url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
	url(r'^cr/(add|del|mod|)?$', views.TeachingResourse),
	url(r'^acs/(automatic)?$', views.CourseArrange),
	url(r'^mca/(add_cl|del_cl|)?$', views.CourseApply),
	url(r'^(admin|teacher)?$', views.Index),
	url(r'^tcs/', views.CourseSearch),
	url(r'^ci/', views.ClassroomInquiry),
	url(r'^course/(add_cz|del_cz|add_cl|del_cl|)?$', views.CourseOperation),
	url(r'^logout/', views.Logout),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 

djcode/djcode/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.views as auth_views
from IMS.views import startup
from djcode import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns #by SMS

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ims/', include('IMS.urls')),
    url(r'^SM/', include('dbtest.urls')), #by SMS
    url(r'^$', startup),
    url(r'^ACS/', include('ACS.urls')),
    #url(r'^', include('teacher.url')), #by OnlineTest
]

urlpatterns += staticfiles_urlpatterns() #by SMS

djcode/classChoose/models.py
# -*- coding: utf-8 -*-
from IMS.models import *

# Create your models here.
class scheme_info(models.Model):
    id = models.CharField(max_length=50,primary_key=True)
    student = models.ForeignKey(Student_user)
    course = models.ForeignKey(Course_info,related_name='scheme_course')
    state = models.IntegerField(default=0)
    def __str__(self):
        return (self.id)

class choose_time(models.Model):
    id = models.CharField(max_length=10,primary_key=True)
    start_time = models.CharField(max_length=50)
    end_time = models.CharField(max_length=50)
    buXuan_start_time = models.CharField(max_length=50)
    buXuan_end_time = models.CharField(max_length=50)

class buXuan_info(models.Model):
    id=models.CharField(max_length=10,primary_key=True)
    student = models.ForeignKey(Student_user)
    Class = models.ForeignKey(Class_info)
    reason = models.CharField(max_length=300)

class college_demand(models.Model):
    id = models.CharField(max_length=10,primary_key=True)
    college = models.CharField(max_length=50)
    majorCourse_demand = models.IntegerField(default=0)
    optionCourse_demand = models.IntegerField(default=0)
    generalCourse_demand = models.IntegerField(default=0)

class pingjia(models.Model):
    id =models.CharField(max_length=10,primary_key=True)
    student = models.ForeignKey(Student_user)
    Class = models.ForeignKey(Class_info)
    dengji = models.CharField(max_length=10)

class count(models.Model):
    id = models.CharField(max_length=10,primary_key=True)
    value = models.IntegerField(default=0)

djcode/dbtest/models.py
# -*- coding: utf-8 -*-
__author__ = 'skar'
from IMS.models import *

class TempTable(models.Model):
    # faculty_id = models.ForeignKey(Faculty_user)
    student_id = models.ForeignKey(Student_user)
    class_id = models.ForeignKey(Class_info)
    """ the above three should be modified to ForeignKey
        not sure if class_id is a primary of class_info
         in IMS
    """
    score = models.FloatField()

    class Meta:
        ordering = ["class_id"]

    def __str__(self):
        return 'score of student %s in class %s' \
               % (self.student_id, self.class_id)


class MessageTable(models.Model):
    message_id = models.CharField(max_length=50)
    from_faculty_id = models.ForeignKey(Faculty_user, related_name='%(class)s_from')
    to_faculty_id = models.ForeignKey(Faculty_user, related_name='%(class)s_to')
    student_id = models.ForeignKey(Student_user)
    class_id = models.ForeignKey(Class_info)
    old_score = models.FloatField()
    new_score = models.FloatField()
    reason = models.CharField(max_length=200)
    status = models.IntegerField(default=0)

    class Meta:
        ordering = ["message_id"]

    def __str__(self):
        return 'message on student %s, from faculty %s to %s' \
               % (self.student_id, self.from_faculty_id, self.to_faculty_id)


class ScoreTable(models.Model):
    class_id = models.ForeignKey(Class_info)
    student_id = models.ForeignKey(Student_user)

    score = models.FloatField()

    class Meta:
        ordering = ["class_id"]

    def __str__(self):
        return 'score of student %s in class %s' \
               % (self.student_id, self.class_id)


class User(models.Model):
    xlsx_file = models.FileField(upload_to='./upload/')

#This class should be get from group of "Choose course"
class Scheme_info(models.Model):
    """
    | class_id | id | state |
    |---|---|---|
    | CHARACTER(10) | CHARACTER(8) |  {-2,-1,0,1,2} |
    """
    student_id = models.ForeignKey(Student_user)
    id = models.ForeignKey(Course_info,related_name='scheme_course', primary_key=True)
    state = models.IntegerField(default=0)
    class Meta:
        ordering = ["student_id"]
    def __str__(self):
        return (self.id)

djcode/templates/models.py
from django.db import models

# Create your models here.

djcode/templates/views.py
from django.shortcuts import render

# Create your views here.

djcode/templates/adminpage1.html
<!DOCTYPE html>

<html lang="zh-cn">
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap v3.2 Template</title>
  
    <!-- Bootstrap -->
    <link href="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="http://ajax.htmlnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js">
  
    <!-- 引入下面两个库让 IE8 支持 HTML5 元素 -->
    <!-- 警告: Respond.js 通过 file:// 浏览的时候不能正常工作！-->
    <!--[if lt IE 9]>
      <script src="http://apps.bdimg.com/libs/html5shiv/3.7/html5shiv.min.js"></script>
      <script src="http://apps.bdimg.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
	<script>
	$(document).ready(function(){
		{% for class in classes %} 
		$("button#{{class.name}}").click(function(){
			
			
		});
		{% endfor %}  
	});
	</script>
 </head>
 
	<body>
	
		<div class="collapse navbar-collapse" id="example-navbar-collapse">
		<ul class="nav navbar-nav">
		
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					培养方案模块 <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><a id = "set_training_plan"href="http://127.0.0.1:8000/trainning_plan">培养方案制定</a></li>
					<li class="divider">
					<li><a id = "check_training_plan" href="http://127.0.0.1:8000/show_plan">查看培养方案</a></li>
					
				</ul>
			</li>
			
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					选课模块 <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><a id = "choose_class"href="http://127.0.0.1:8000/choose_class">选课</a></li>
					<li class="divider">
					<li><a id = "class_search"href="http://127.0.0.1:8000/course_search">选课搜索引擎</a></li>
					<li class="divider">
					<li><a id = "check_class_table"href="http://127.0.0.1:8000/show_class">查看课表</a></li>
					
				</ul>
			</li>
			<li><a id = "teacher_model"href="#">教师模块</a>
			<li><a id = "admin_model"href="http://127.0.0.1:8000/admin_page1">管理员模块</a>
			<li><a id = "return_daohang"href="#">返回导航</a>
			
			
			
			
			
		</div>
	
	<div class="container">
	<h2>管理员模块</h2>
	<p>管理员：{{admin.name}}  您好。</p>
	
	
	<div id="time_control">
	<p>您可以在这里设置选课起止时间：</p>
	<form method='post'>
		{% csrf_token %}
			<input type="text"  name="start_time" placeholder="选课开始时间">
			<input type="text"  name="sift_time" placeholder="选课结束时间">
			<input type="text"  name="buxuan_time" placeholder="补选开始时间">
			<input type="text"  name="end_buxuan_time" placeholder="补选结束时间">
		{{ form }}
		<input type="submit" value="提交">
	</form>
		
	</div>
	
	<div class="table-responsive">
		<table class="table table-striped table-bordered">
		<caption>您可以管理的课程列表</caption>
		<thead>
		<tr>
			
			<th>课程名称</th>
			<th>课程代码</th>
			<th>任课教师</th>
			<th>上课时间</th>
			<th>课程容量</th>
			<th>课程余量</th>
			<th>进入管理</th>
			<th>查看补选</th>
		</tr>
		</thead>
		<tbody>
		{% block content %}  
		{% for class in classes %}  
        <tr>
         <td>{{class.course.name}}</td>
         <td>{{class.id}}</td>
         <td>{{class.teacher_name}}</td>
		 <td>{{class.time}}</td>
		 <td>{{class.capacity}}</td>
		 <td>{{class.remain}}</td>
		 <td>
			<button type="button" id="{{class.name}}"  class="btn btn-default" >
				<a href="http://127.0.0.1:8000/ad2/?class_id={{class.id}}&id={{admin.id}}">
				进入管理</a>
			</button>

		 </td>
		 <td>
		 	<button type = "button" id = "{{class.name}}" class = "btn btn-default">
		 		<a href = "http://127.0.0.1:8000/buxuan/?class_id={{class.id}}">
		 			查看补选</a>
		 	</button>


		 </td>
        </tr>
		{% endfor %}  
		{% endblock %}
		</tbody>
		</table>
	</div>
	
	
	
	
	</div>
		<script>
        var LocString = String(window.document.location.href); 
		function getQueryStr(str) { 
			var rs = new RegExp("(^|)" + str + "=([^&]*)(&|$)", "gi").exec(LocString), tmp; 
			if (tmp = rs) { 
			return tmp[2]; 
			} 
			// parameter cannot be found 
			return ""; 
		} 
		
		var div = document.getElementById('set_training_plan'); 
		div.setAttribute("href", "http://127.0.0.1:8000/trainning_plan/?id="+getQueryStr("id")); 
		var div2 = document.getElementById('check_training_plan'); 
		div2.setAttribute("href", "http://127.0.0.1:8000/trainning_plan/?id="+getQueryStr("id")); 
		var div3 = document.getElementById('class_search'); 
		div3.setAttribute("href", "http://127.0.0.1:8000/course_search/?id="+getQueryStr("id")); 
		var div4 = document.getElementById('check_class_table'); 
		div4.setAttribute("href", "http://127.0.0.1:8000/show_class/?xh="+getQueryStr("id")); 
		var div5 = document.getElementById('teacher_model'); 
		div5.setAttribute("href", "http://127.0.0.1:8000/teacher_model/?id="+getQueryStr("id")); 
		var div6 = document.getElementById('admin_model'); 
		div6.setAttribute("href", "http://127.0.0.1:8000/ad1/?id="+getQueryStr("id")); 
		var div7 = document.getElementById('return_daohang'); 
		div7.setAttribute("href", "http://127.0.0.1:8000/daohang/?id="+getQueryStr("id")); 
		var div8 = document.getElementById('choose_class'); 
		div8.setAttribute("href", "http://127.0.0.1:8000/trainning_plan/?id="+getQueryStr("id"));  
    </script>
	<script src="http://apps.bdimg.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://apps.bdimg.com/libs/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	</body>
</html>

djcode/templates/chooseextra.html
<html>
<head>
	<title>补选申请</title>
		<link href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
		<link href="http://v3.bootcss.com/examples/dashboard/dashboard.css" rel="stylesheet">
		<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
	    
	
		<script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
		<script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
		<link rel="icon" href="http://v3.bootcss.com/favicon.ico">

		<style> 
		#choosereason { 
				width:600px;
				height:300px; 
                }
		</style>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example-navbar-collapse">
		<span class="sr-only">切换导航</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="#">选课子系统</a>
	</div>
	<div class="collapse navbar-collapse" id="example-navbar-collapse">
		<ul class="nav navbar-nav">
		
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					培养方案模块 <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><a id = "set_training_plan"href="http://127.0.0.1:8000/trainning_plan">培养方案制定</a></li>
					<li class="divider">
					<li><a id = "check_training_plan" href="http://127.0.0.1:8000/show_plan">查看培养方案</a></li>
					
				</ul>
			</li>
			
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					选课模块 <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><a id = "choose_class"href="http://127.0.0.1:8000/choose_class">选课</a></li>
					<li class="divider">
					<li><a id = "class_search"href="http://127.0.0.1:8000/course_search">选课搜索引擎</a></li>
					<li class="divider">
					<li><a id = "check_class_table"href="http://127.0.0.1:8000/show_class">查看课表</a></li>
					
				</ul>
			</li>
			<li><a id = "teacher_model"href="#">教师模块</a>
			<li><a id = "admin_model"href="http://127.0.0.1:8000/admin_page1">管理员模块</a>
			<li><a id = "return_daohang"href="#">返回导航</a>
			
			
			
			
			
	</div>
	</nav>
	
	<div>
		<h2>
			您要补选的课程是 {{class.name}}
		</h2>
		<form id = "reason" method = "POST">
			{% csrf_token %}
			<div class="form-group">
			<label for="name">补选理由</label>
			<input type="text" class="form-control" id="choosereason" name="choosereason" placeholder="请输入理由" width=90px  height=25px>
			</div>
		
			<button type="submit" class="btn btn-default">提交</button>
		</form>
		
    
	</div>
	<script>
        var LocString = String(window.document.location.href); 
		function getQueryStr(str) { 
			var rs = new RegExp("(^|)" + str + "=([^&]*)(&|$)", "gi").exec(LocString), tmp; 
			if (tmp = rs) { 
			return tmp[2]; 
			} 
			// parameter cannot be found 
			return ""; 
		} 
	
		var div = document.getElementById('set_training_plan'); 
		div.setAttribute("href", "http://127.0.0.1:8000/trainning_plan/?id="+getQueryStr("xh")); 
		var div2 = document.getElementById('check_training_plan'); 
		div2.setAttribute("href", "http://127.0.0.1:8000/trainning_plan/?id="+getQueryStr("xh")); 
		var div3 = document.getElementById('class_search'); 
		div3.setAttribute("href", "http://127.0.0.1:8000/course_search/?id="+getQueryStr("xh")); 
		var div4 = document.getElementById('check_class_table'); 
		div4.setAttribute("href", "http://127.0.0.1:8000/show_class/?xh="+getQueryStr("xh")); 
		var div5 = document.getElementById('teacher_model'); 
		div5.setAttribute("href", "http://127.0.0.1:8000/teacher_model/?id="+getQueryStr("xh")); 
		var div6 = document.getElementById('admin_model'); 
		div6.setAttribute("href", "http://127.0.0.1:8000/ad1/?id="+getQueryStr("xh")); 
		var div7 = document.getElementById('return_daohang'); 
		div7.setAttribute("href", "http://127.0.0.1:8000/daohang/?id="+getQueryStr("xh")); 
		var div8 = document.getElementById('choose_class'); 
		div8.setAttribute("href", "http://127.0.0.1:8000/trainning_plan/?id="+getQueryStr("xh"));  
    </script>
	
</body>
</html>

djcode/templates/score_alert.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{{alert_info}}</title>
</head>
<body>
<h1>
{{ alert_info }}
</h1>
<h2>
    <p>
        <a href="{{ refresh_url }}">
            两秒钟后将跳转，如果长时间没有响应请直接点击
        </a>
    </p>
</h2>
<meta http-equiv="refresh" content="2;url={{ refresh_url }}">
</body>
</script>

djcode/templates/score_commit.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>成绩登记</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap-theme.min.css">
    <script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/js/d3.min.js"></script>
</head>
<body>
<div class="container-fluid">
    <ul class="nav nav-tabs">
      <li role="presentation"><a href="/SM/query">成绩查询</a></li>
      <li role="presentation" class="active"><a href="/SM/commit">成绩登记</a></li>
      <li role="presentation"><a href="/SM/modification">成绩修改</a></li>
      <li role="presentation"><a href="/SM/logout">退出</a></li>
      <li role="presentation"><a href="/">返回主系统</a></li>
    </ul>
    <div class="row">
        <div class="col-md-2">
            <h3>尚未提交的课程</h3>
            <ul class="nav nav-pills nav-stacked" id="courseList">
<!--                   <li role="presentation" class="active"><a href="#">英语口语</a></li>
                  <li role="presentation"><a href="#">英语写作</a></li>
                  <li role="presentation"><a href="#">英美文学</a></li> -->
            </ul>
        </div>
        <div class="col-md-7">     

            <table class="table">
                <tr>
                    <th>课程代码</th>
                    <th>课程名称</th>
                    <th>学分</th>
                </tr>
                <tr id="infoTable">
<!--                     <td>(2012-2013-2)-04810020-0096419-1</td>
                    <td>英语口语</td>
                    <td>1.0</td> -->
                </tr>
            </table>

            <a id="downloadButton" href=""><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-download" aria-hidden="true"></span>下载成绩单</button></a>
            <form id="uploadButton" action="" method="post" enctype="multipart/form-data">{% csrf_token %}<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-upload" aria-hidden="true"></span>上传成绩单</button><input id="id_xlsx_file" name="xlsx_file" type="file" /></form>
            <a id="commitButton" href=""><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>正式提交</button></a>  
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>学号</th>
                    <th>姓名</th>
                    <th>成绩</th>
                    <th>绩点</th>
                    <th>修改成绩</th>
                </tr>
                </thead>
                <tbody id="studentTable">
<!--                 <tr>
                    <td>3120000001</td>
                    <td>张三</td>
                    <td>87</td>
                    <td>4.20</td>
                </tr>
                <tr>
                    <td>3120000002</td>
                    <td>李四</td>
                    <td>88</td>
                    <td>4.30</td>
                </tr> -->
                </tbody>                
            </table> 
       </div>

        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">成绩修改工具栏</div>
                <div class="panel-body">
                    <form id="editScoreForm" action="" method="post">
                        {% csrf_token %}
                        <div class="form-group" id="EditCourseID">
                            <label for="EditCourseID">教学班号</label>
                            <input name="classID" id="id_classID" type="text" class="form-control" readonly="readonly" value="">
                        </div>
                        <div class="form-group" id="EditCourseName" >
                            <label for="EditCourseName">课程名称</label>
                            <input type="text" class="form-control"readonly="readonly" value="">
                        </div>
                        <div class="form-group" id="EditStudentID">
                            <label for="EditStudentID">学生学号</label>
                            <input name="studentID" id="id_studentID" type="text" class="form-control"readonly="readonly" value="">
                        </div>                  
                        <div class="form-group" id="EditStudentName">
                            <label for="EditStudentName">学生姓名</label>
                            <input type="text" class="form-control"readonly="readonly" value="">
                        </div>
                        <div class="form-group" id="EditOldScore">
                            <label for="EditOldScore">原成绩</label>
                            <input type="text" class="form-control"readonly="readonly" value="">
                        </div>
                        <div class="form-group" id="EditNewScore">
                            <label for="EditNewScore">新成绩</label>
                            <input name="newScore" id="id_newScore" type="text" class="form-control">
                        </div>

                        <!--<a id="editButton" href=""><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>提交修改</button></a>-->
                        <button type="submit" class="btn btn-default" value="submit">提交修改</button>
                    </form>
                </div>
            </div>

    </div>
</div>
<script type="text/javascript">
    //TODO
    d3.json('/SM/B_teacher_temp_query/',function(data){ // 查临时表获取未commit的课程
        console.log(data);
        courseInfo = data;
        updateList(data);   // 更新未提交课程的list
    });

var courseInfo;
var theCourseInfo;
var studentScore;

function updateList(data){  // 左侧选择未commit的课程
    d3.select("#courseList").selectAll("li").remove();
    d3.select("#courseList").selectAll("li")
        .data(data)
        .enter().append("li")
        .attr("role","presentation")
        .html(function(d){return '<a href="#" onclick="selectCourse(\'' + d.classID +'\')">' + d.courseName + "</a>"});    // 选取后，跳转到对应课程的上传界面，call selectCourse

        // .html(function(d){return '<a href="#">' + d.courseName + "</a>"});
    // var firstCourse = d3.select("#courseList").select("li")
    // if(firstCourse.size() >= 1){
    //     firstCourse.attr("class","active");
    // }
}

function selectCourse(classID){ // update
    console.log(classID);
    console.log(courseInfo);
    var course;
    for (var i = courseInfo.length - 1; i >= 0; i--) {
        course = courseInfo[i];
        if(course.classID == classID)
            break;
    }
    if(i<0){    // exception
        console.log("Cannot find the course");
        return;
    }
    theCourseInfo = course;
    d3.select("#downloadButton").attr("href","/SM/B_download_xlsx/" + course.classID); // download previously uploaded excel
    d3.select("#uploadButton").attr("action","/SM/B_upload_xlsx/" + course.classID);   // upload excel
    d3.select("#commitButton").attr("href","/SM/B_finalCommit/"+course.classID);   // commit uploading file
    updateInfoTable(course);    // 更新当前显示的课程简要信息
    updateStudentTable(course.classID);    // call function to update students' scores
}

function updateStudentTable(classID){
    // TODO
    d3.json("/SM/B_temp_class_score_query/"+classID,function(data){
        console.log(classID);
        studentScore = data;

        d3.select("#studentTable").selectAll("tr").remove();
        d3.select("#studentTable").selectAll("tr")
            .data(data)
            .enter().append("tr")
            .html(function (d) {
            str = '';
            str += "<td>" + d.studentID + "</td>";  // 学号
            str += "<td>" + d.studentName + "</td>";    // 姓名
            str += "<td>" + d.score + "</td>";  // 分数
            str += "<td>" + d.gradePoint + "</td>"; // 绩点 
            str += '<td><button class="btn btn-default btn-sm" onclick="createForm(\'' + classID + '\' , \'' + d.studentID + '\')">修改</button></td>';
            return str;
        });
    })
}

function updateInfoTable(course){   // 更新右上方课程信息
    d3.select("#infoTable").selectAll("td").remove();
    d3.select("#infoTable").selectAll("td")
        .data([course.classID, course.courseName, course.credits]) // 显示课程号、课程名称、学分
        .enter().append("td")
        .text(function(d){return d});
}


function createForm(classID, studentID){    // generate a new request form
    
    console.log(classID);
    console.log(studentID);
    
    console.log(studentScore);
    console.log(courseInfo);

    var form = [];

    var i;
    var cTmp;
    for (i = courseInfo.length - 1; i >= 0; i--) { // 若选择修改的记录与现在显示的一致，则break 
        cTmp = courseInfo[i];
        if(theCourseInfo.classID == classID)
            break;
    }
    form[0] = theCourseInfo.classID;
    form[1] = theCourseInfo.courseName;

    var sTmp;
    for (i = studentScore.length - 1; i >= 0; i--) { // 若选择修改的记录与现在显示的一致，则break 
        sTmp = studentScore[i];
        if(sTmp.studentID == studentID)
            break;
    }
    form[2] = studentScore[i].studentID;
    form[3] = studentScore[i].studentName;
    form[4] = studentScore[i].score;

    console.log([form]);

    // modify the form in html
    document.getElementById('EditCourseID').innerHTML = '<label for="EditCourseID">教学班号</label><input type="text" class="form-control" readonly="readonly" value="' + form[0] + '">';
    document.getElementById('EditCourseName').innerHTML = '<label for="EditCourseName">课程名称</label><input type="text" class="form-control"readonly="readonly" value="' + form[1] + '">';
    document.getElementById('EditStudentID').innerHTML = '<label for="EditStudentID">学生学号</label><input type="text" class="form-control"readonly="readonly" value="' + form[2] + '">';
    document.getElementById('EditStudentName').innerHTML = '<label for="EditStudentName">学生姓名</label><input type="text" class="form-control"readonly="readonly" value="' + form[3] + '">';
    document.getElementById('EditOldScore').innerHTML = '<label for="EditOldScore">原成绩</label><input type="text" class="form-control"readonly="readonly" value="' + form[4] + '">';

    d3.select("#editScoreForm").attr('action',"/SM/B_online_save/" + form[2] + '/' + form[0]);
        
}

</script>
</div>
</body>
</html>

djcode/templates/score_login.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>临时登录</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap-theme.min.css">
    <script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
</head>
<body>

<form method="post">
<!-- 	django post csrf -->
  {% csrf_token %}
  {{ form }}
  <button type="submit" class="btn btn-default">提交</button>
</form>
</body>
</html>